name: Crontab UI
on:
  push:
    branches:
      - main

jobs:
  docker-package:
    runs-on: ubuntu-latest 
    permissions: write-all
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images
      run: |
        docker build . --build-arg --rm -t ghcr.io/samuelloza/crontab-ui:develop

    - name: Push Docker image to registry
      run: |
        docker push ghcr.io/samuelloza/crontab-ui:develop
